version: '3'
services:
  chocolates:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - "logsvolume:/usr/src/app/logs"
    restart: "on-failure"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DBPORT=${DBPORT}
  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
    command: --port ${DBPORT} --logpath /var/log/mongodb/mongodb.log
    volumes:
      - "logsvolume:/var/log/mongodb"
      - "datavolume:/data/db"

    
volumes:
  logsvolume:
  datavolume:
